spring.application.name=inception

notification.email=true
notification.sms=true

spring.h2.console.enabled=true
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.url=jdbc:h2:file:/Users/saurabhnakade/Downloads/inception/db
spring.jpa.hibernate.ddl-auto=create

#debug=true

# Module 1 Assignment
frosting=chocolate
syrup=strawberry